### ISSUE TITLE
Select2 4.0

### ISSUE THREAD

**Issue by jessevl** [comerc/placecomplete#2]
Since the original project seems dead I hope you don't mind me asking here as you seem to be fairly active in modifying your own placecomplete fork. 

Select2 is undergoing a major rewrite for version 4.0 (it is still in beta) but they seem to be abandoning the 3.5.2 stable version already. Unfortunately placecomplete is not compatible with 4.0 as they have changed some major things (see http://select2.github.io/announcements-4.0.html). They do provide some compatibility modules in the full version but it doesn't seem to work anyway.

Is there any chance that you will update your fork of placecomplete to work with 4.0? Or how much work would it be?

Thanks!

**Comment by comerc** [comment]
You may use [selectize](https://github.com/brianreavis/selectize.js) with [placecomplete plugin](https://github.com/comerc/selectize-placecomplete). It is true way :)
